name: Run tests
on: push
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry lock --no-update
          poetry install --with dev
      - name: run tests
        run: poetry run python -m unittest discover .
      - name: run type checking
        run: poetry run mypy fib_py